"""New changes applied successfully!!😊

Revision ID: 11815cf08ec9
Revises: 2d9057932d5b
Create Date: 2024-04-24 20:07:14.651019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11815cf08ec9'
down_revision = '2d9057932d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('phonenumber')
        batch_op.drop_column('gender')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
