"""New changes applied successfully!!😊

Revision ID: 4a5cf305fcbe
Revises: 0e5257f536a4
Create Date: 2024-04-26 11:21:21.043223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a5cf305fcbe'
down_revision = '0e5257f536a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.create_unique_constraint(None, ['password_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###
