"""New changes applied successfully!!😊

Revision ID: 51a8cfad0d62
Revises: 0c56f7a55126
Create Date: 2024-05-08 12:03:28.430329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a8cfad0d62'
down_revision = '0c56f7a55126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
